# Generated by Django 4.2.6 on 2023-10-20 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountability_score', '0002_usermetrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermetrics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='accountabilityscore',
            table='accountability_score',
        ),
    ]
