# Generated by Django 4.2.6 on 2023-10-20 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountability_score', '0003_alter_usermetrics_user_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountabilityscore',
            table=None,
        ),
    ]
