# Generated by Django 4.2.6 on 2023-10-20 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability_score', '0005_alter_accountabilityscore_id_alter_dailyscorelog_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermetrics',
            name='consistency',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='usermetrics',
            name='task_retention',
            field=models.FloatField(default=0.95, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
