# Generated by Django 4.2.6 on 2023-10-20 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability_score', '0006_alter_usermetrics_consistency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountabilityscore',
            name='prev_score',
            field=models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(850)]),
        ),
    ]
