# Generated by Django 4.2.6 on 2023-10-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability_score', '0007_accountabilityscore_prev_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyscorelog',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
