# Generated by Django 4.2.6 on 2023-11-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tag_created_at_tag_updated_at_alter_tag_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='time_of_day',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
