# Generated by Django 4.2.6 on 2023-11-11 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_duration_task_start_time_task_time_of_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time_of_day',
        ),
    ]
