# Generated by Django 4.2.7 on 2023-11-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_taskcompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Not Started', 'NOT_STARTED'), ('Completed', 'COMPLETE'), ('In Progress', 'IN_PROGRESS')], default='Not Started', max_length=20),
        ),
    ]
