# Generated by Django 4.2.7 on 2023-11-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='days_of_week',
            field=models.CharField(default='Sunday', max_length=100),
            preserve_default=False,
        ),
    ]
