# Generated by Django 4.2.7 on 2023-11-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_task_days_of_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='days_of_week',
        ),
        migrations.AddField(
            model_name='task',
            name='days_of_week',
            field=models.ManyToManyField(to='tasks.day'),
        ),
    ]
