# Generated by Django 4.2.7 on 2023-11-29 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_taskstatus_remove_task_status_delete_taskcompletion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstatus',
            name='completed',
        ),
    ]
